name: oggm_env
channels:
  - conda-forge
dependencies: # these are provided by oggm
  - numpy
  - scipy
  - pandas
  - shapely
  - matplotlib
  - Pillow
  - netcdf4
  - scikit-image
  - configobj
  - xarray
  - pytest
  - dask
  - bottleneck
  - pyproj
  - cartopy
  - geopandas
  - rasterio
  - rioxarray
  - seaborn
  - pytables
  - salem
  - motionless
  - pip
  - pip:
    - joblib
    - progressbar2
    - oggm
    - xarray-regrid #this one is from Aguayo et al. (2024)'s workflow but is only on pip 

  #adding dependencies from Aguayo et al. (2024)'s workflow - all available on Conda 
  - psutil
  - tqdm 
  - esmpy
  - xesmf 
  - xclim
  - intake 
  - gcsfs 
  - cftime 
  - regionmask 
  - ipykernel